[option]
exclude_paths = ["ip/.*"]

[rules]
case_default = true
enum_with_type = true
for_with_begin = true
function_same_as_system_function = true
function_with_automatic = true
generate_for_with_label = true
generate_if_with_label = true
generate_keyword_forbidden = false
generate_keyword_required = true
genvar_declaration_in_loop = true
genvar_declaration_out_loop = false
if_with_begin = true
inout_with_tri = false
input_with_var = false
legacy_always = true
level_sensitive_always = true
loop_variable_declaration = true
non_ansi_module = true
output_with_var = false
parameter_in_package = true
priority_keyword = true
tab_charactor = true
unique0_keyword = true
unique_keyword = true
wire_reg = true
